# Generated by Django 5.0.7 on 2024-08-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="reply",
            field=models.TextField(blank=True, null=True),
        ),
    ]
