# Generated by Django 5.0.7 on 2024-08-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_ticket_reply"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="status",
        ),
    ]
