# Generated by Django 5.0.7 on 2024-08-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_remove_ticket_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="users"),
        ),
    ]
