# Generated by Django 5.0.7 on 2024-12-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_ticket_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
