version: '3.9'

services:
  db:
    image: postgres:12-buster
    restart: always
    hostname: postgres_db
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - '5432:5432'

  web:
    build: .
    command: /bin/bash -c 'python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000'
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: 5432

volumes:
  postgres_data:
